%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2021, Diogo Costa, diogo.pinhodacosta@canada.ca
% This file is part of WebCrawler tool.

% This program, WebCrawler tool, is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) aNCOLS later version.

% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.

% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function countries_list = listing_countries() 

countries_list = {
    'Afghanistan',...
    'Albania',...
    'Algeria',...
    'Andorra',...
    'Angola',...
    'Antigua and Barbuda',...
    'Argentina',...
    'Armenia',...
    'Australia',...
    'Austria',...
    'Azerbaijan',...
    'The Bahamas',...
    'Bahrain',...
    'Bangladesh',...
    'Barbados',...
    'Belarus',...
    'Belgium',...
    'Belize',...
    'Benin',...
    'Bhutan',...
    'Bolivia',...
    'Bosnia and Herzegovina',...
    'Botswana',...
    'Brazil',...
    'Brunei',...
    'Bulgaria',...
    'Burkina Faso',...
    'Burundi',...
    'Cabo Verde',...
    'Cambodia',...
    'Cameroon',...
    'Canada',...
    'Central African Republic',...
    'Chad',...
    'Chile',...
    'China',...
    'Colombia',...
    'Comoros',...
    'Congo, Democratic Republic of the',...
    'Congo, Republic of the',...
    'Costa Rica',...
    'Ivory Coast',...
    'Croatia',...
    'Cuba',...
    'Cyprus',...
    'Czech Republic',...
    'Denmark',...
    'Djibouti',...
    'Dominica',...
    'Dominican Republic',...
    'East Timor (Timor-Leste)',...
    'Ecuador',...
    'Egypt',...
    'El Salvador',...
    'Equatorial Guinea',...
    'Eritrea',...
    'Estonia',...
    'Eswatini',...
    'Ethiopia',...
    'Fiji',...
    'Finland',...
    'France',...
    'Gabon',...
    'The Gambia',...
    'Georgia',...
    'Germany',...
    'Ghana',...
    'Greece',...
    'Grenada',...
    'Guatemala',...
    'Guinea',...
    'Guinea-Bissau',...
    'Guyana',...
    'Haiti',...
    'Honduras',...
    'Hungary',...
    'Iceland',...
    'India',...
    'Indonesia',...
    'Iran',...
    'Iraq',...
    'Ireland',...
    'Israel',...
    'Italy',...
    'Jamaica',...
    'Japan',...
    'Jordan',...
    'Kazakhstan',...
    'Kenya',...
    'Kiribati',...
    'Korea, North',...
    'Korea, South',...
    'Kosovo',...
    'Kuwait',...
    'Kyrgyzstan',...
    'Laos',...
    'Latvia',...
    'Lebanon',...
    'Lesotho',...
    'Liberia',...
    'Libya',...
    'Liechtenstein',...
    'Lithuania',...
    'Luxembourg',...
    'Madagascar',...
    'Malawi',...
    'Malaysia',...
    'Maldives',...
    'Mali',...
    'Malta',...
    'Marshall Islands',...
    'Mauritania',...
    'Mauritius',...
    'Mexico',...
    'Micronesia, Federated States of',...
    'Moldova',...
    'Monaco',...
    'Mongolia',...
    'Montenegro',...
    'Morocco',...
    'Mozambique',...
    'Myanmar (Burma)',...
    'Namibia',...
    'Nauru',...
    'Nepal',...
    'Netherlands',...
    'New Zealand',...
    'Nicaragua',...
    'Niger',...
    'Nigeria',...
    'North Macedonia',...
    'Norway',...
    'Oman',...
    'Pakistan',...
    'Palau',...
    'Panama',...
    'Papua New Guinea',...
    'Paraguay',...
    'Peru',...
    'Philippines',...
    'Poland',...
    'Portugal',...
    'Qatar',...
    'Romania',...
    'Russia',...
    'Rwanda',...
    'Saint Kitts and Nevis',...
    'Saint Lucia',...
    'Saint Vincent and the Grenadines',...
    'Samoa',...
    'San Marino',...
    'Sao Tome and Principe',...
    'Saudi Arabia',...
    'Senegal',...
    'Serbia',...
    'Seychelles',...
    'Sierra Leone',...
    'Singapore',...
    'Slovakia',...
    'Slovenia',...
    'Solomon Islands',...
    'Somalia',...
    'South Africa',...
    'Spain',...
    'Sri Lanka',...
    'Sudan',...
    'Sudan, South',...
    'Suriname',...
    'Sweden',...
    'Switzerland',...
    'Syria',...
    'Taiwan',...
    'Tajikistan',...
    'Tanzania',...
    'Thailand',...
    'Togo',...
    'Tonga',...
    'Trinidad and Tobago',...
    'Tunisia',...
    'Turkey',...
    'Turkmenistan',...
    'Tuvalu',...
    'Uganda',...
    'Ukraine',...
    'United Arab Emirates',...
    'United Kingdom',...
    'United States',...
    'Uruguay',...
    'Uzbekistan',...
    'Vanuatu',...
    'Vatican City',...
    'Venezuela',...
    'Vietnam',...
    'Yemen',...
    'Zambia',...
    'Zimbabwe'};
end

