%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2021, Diogo Costa, diogo.pinhodacosta@canada.ca
% This file is part of WebCrawler tool.

% This program, WebCrawler tool, is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) later version.

% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.

% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Convert to singular words
function keyword_i = to_lowercase_and_put_singular(keyword_i)


    keyword_i = lower(keyword_i);
    if strcmp( keyword_i(end-1:end), 'es') &&...
            ~contains(keyword_i,'hydrates') &&...
            ~contains(keyword_i,'lakes') &&...
            ~contains(keyword_i,'services') &&...
            ~contains(keyword_i,'resources') &&...
            ~contains(keyword_i,'great lakes')
        
            keyword_i = keyword_i(1:end-2);
        
    elseif strcmp( keyword_i(end), 's') &&...
            ~contains(keyword_i,'mars') &&...
            ~contains(keyword_i,'hydrates') &&...
            ~contains(keyword_i,'analysis') &&...
            ~contains(keyword_i,'services') &&...
            ~contains(keyword_i,'activities') &&...
            ~contains(keyword_i,'nutrients') &&...
            ~contains(keyword_i,'resources') &&...
            ~contains(keyword_i,'lakes') &&...
            ~contains(keyword_i,'phosphorus') &&...
            ~contains(keyword_i,'great lakes')
        
        keyword_i = keyword_i(1:end-1);
    end
    
end