
% To Remove from Nutrients and Climate Change

maybe_remove_general = [3, 6, 10, 14, 15, 27, 37, 38, 54, 55, 63, 68,17, 26,...
    24, 49, 55, 61, 154, 174, 251, 253, 254, 255,257, 260, 261, 267, 268,274,...
    275, 276, 278, 281, 283, 286, 294,296, 302,304, 306, 309, 310,314, 315, 316,...
    320, 321, 323, 324, 328, 331, 332,379, 411, 425, 437];


sure_remove_general = [4, 42, 62, 73, 77, 83, 91,102, 105, 113, 114,116,122,...
    123,125,136, 143,147, 148, 150, 153 ,157, 162, 163, 170,173, 180,184, 187,...
    189,190,191,19,196,197,198,20,208,211,213,214,215,216,219,220,223,224,...
    225,228,229, 232,239,247,335,336,338,337,339,341,344,351,352,361, 363,365,...
    369,371,372,373,375,377, 380,384,390,391,392,393,394,396,397,398,400,404,405,...
    409,410,413,419, 420, 421, 427, 428, 429, 436, 443, 445, 447, 448, 450, 451,...
    453, 455, 461, 468, 469, 484, 485, 489, 490, 491, 493, 494, 497,498, 503, 504,...
    509, 512, 513, 514, 516, 520, 522, 523, 532, 538, 542, 546, 550, 554, 556, 557,...
    558, 559, 560, 561, 562, 563, 567, 569];


maybe_remove_by_country = [10, 11, 12, 18, 28, 32, 40, 58,201,207,210,211,215,216,...
    218,219,230,231,234,242,243,245,249,252,253,256,259,287,380, 382];

sure_remove_general = [17, 26, 24, 49, 55, 61,68,74 ,77,79,80,81,91,95,97,98,99,...
    100,106,107,108,110,111,112,114,116,119,122,125,131,139, 140,141, 145,146,...
    154,156, 164,169, 173,175, 182,183, 187, 188, 192,261, 271,275,276,278,279,...
    282, 285,286, 291,293, 294,296,297,298, 301,302,311, 315,317,319,321,...
    322,329,332, 349, 356, 358, 359, 367, 368, 381,398, 399, 400, 401, 407,...
    409, 410, 412, 418, 419, 420, 421, 429, 433, 434, 436, 437, 438, 441, 444];


%% NUTRIENTS AND CLIMATE CHANGE REPORT            
%{
folder_name_to_store_results = 'nutrients_AND_climate_change_SCOPUS';                
main_keyword_searchengine_raw_multiple =[
                                        'DOCTYPE(ar) AND ',...
                                        ...{'TITLE-ABS(',...
                                        'TITLE(',...
                                        '("climate change" OR "global warming")',...
                                        ' AND (nutrient* OR nitrogen* OR *phosph* OR nitrat*)',...
                                        ' AND (river* OR lake* OR wetland OR stream* OR basin* OR watershed* OR runoff OR "run-off" OR reservoir)',...
                                        ' AND NOT ("greenhouse gas*" OR emissions OR methane OR "carbon dioxide" OR "CO<sub>2</sub>" OR "CH<sub>4</sub>")',...
                                        ' AND NOT ("Environment and Climate Change Canada")'...
                                        ' AND NOT (*coral* OR *reef* OR *sea* OR *ocean*)',...
                                        ' AND NOT (*urban* OR *highway* OR "treatment plant" OR *roof*)',...
                                        ')',...
                                        %' AND TITLE-ABS(country_placeholder)'...
                                        ];
                                      
%}


% Second run: Nutrients and climate change review paper
%folder_name_to_store_results = 'nutrients_AND_climate_change_SCOPUS_3';      
%{
folder_name_to_store_results = 'nutrients_AND_climate_change_by_country_SCOPUS_3';
main_keyword_searchengine_raw_multiple =[...
                                    'DOCTYPE(ar)',...
                                    ' AND TITLE(',...
                                       '(nutrient* OR nitrogen* OR *phosph* OR nitrat* OR "water quality")',...
                                        ' AND (',...
                                            '(climate AND (chang* OR variab*))',... 
                                            ' OR "global warming"',... 
                                            ' OR (extreme AND (event* OR precipitation OR rain* OR climat*))',...
                                            ')',...
                                        ' AND NOT (',...
                                            '"use efficienc*" OR socia* OR yield* OR sea OR ocean OR marine OR mortality OR reproduction OR sexual',...
                                            ' OR phenolog* OR biofuel* OR food* OR "ecosystem services"',...
                                        ')',...
                                    ')',...
                                    ' AND TITLE-ABS-KEY(',...
                                       'country_placeholder',...
                                        ' AND NOT (',...
                                        ...    '(river* OR lake* OR wetland OR stream* OR basin* OR watershed* OR runoff OR "run-off" OR reservoir)',... 
                                        ...    ' AND NOT ("greenhouse gas*" OR methane OR "carbon dioxide" OR "CO<sub>2</sub>" OR "CH<sub>4</sub>")',... 
                                            '*coral* OR wave OR *reef* OR oceanogra* OR tsunami* OR tid* OR bathyal OR abyssal OR hadal',... 
                                            ' OR neogene OR miocene OR oligocene OR eocene OR paleo* OR cretaceus or triassic',...
                                        ...    ' OR "renewable energy" OR "solar energy"',...
                                        ...    ' AND NOT (*sea* OR *ocean*)',... 
                                        ...    ' AND NOT (*urban* OR *highway* OR "treatment plant" OR *roof*)',...
                                        ')',...
                                    ')',...
                                        ];
%}

% Permafrost
folder_name_to_store_results = 'permafrost_AND_climate_change_TITLE-ABS-KEY_SCOPUS';                
main_keyword_searchengine_raw_multiple =[...
                                    'DOCTYPE(ar)',...
                                         ' AND TITLE-ABS-KEY(',...     
                                            '(permafrost*)',...
                                            ' AND (',...
                                                 '(climate AND (chang* OR variab* OR trend))',...
                                                   ' OR "global warming"',...
                                                   ' OR (extreme* AND (event* OR precipitation OR rain* OR climat*))',...
                                            ')',...
                                            ' AND NOT (',...
                                                   'methane OR hydrates OR Quaternary OR Pleistocene OR Mars OR carbon-dioxide',...
                                                   ')',...
                                            ')',...
                                        ];


%% GW AND CC REPORT
%{
folder_name_to_store_results = 'groundwater_AND_climate_change_TITLE_SCOPUS';                
main_keyword_searchengine_raw_multiple =[
                                        'DOCTYPE(ar) AND ',...
                                        ...%{'TITLE-ABS(',...
                                        'TITLE(',...
                                        '("climate change" OR "global warming")',...
                                        ' AND (*groundwater* OR *aquifer* OR *subsurface* OR *underground*)',...
                                        ' AND ("Great Lakes" OR "Lake Superior" OR "Lake Michigan" OR "Lake Huron" OR "Lake Erie" OR "Lake Ontario")',...
                                        ' AND NOT ("Environment and Climate Change Canada"))',...
                                        ...%' AND TITLE-ABS(country_placeholder)'...
                                        ];

%}

%{
folder_name_to_store_results = 'groundwater_AND_climate_change_TITLE-ABS-KEY_SCOPUS';                
main_keyword_searchengine_raw_multiple =[
                                        'DOCTYPE(ar) AND ',...
                                        ...%{'TITLE-ABS(',...
                                        'TITLE-ABS-KEY(',...
                                        '("climate change" OR "global warming")',...
                                        ' AND (*groundwater* OR *aquifer* OR *subsurface* OR *underground*)',...
                                        ' AND ("Great Lakes" OR "Lake Superior" OR "Lake Michigan" OR "Lake Huron" OR "Lake Erie" OR "Lake Ontario")',...
                                        ' AND NOT ("Environment and Climate Change Canada"))',...
                                        ...%' AND TITLE-ABS(country_placeholder)'...
                                        ];     
%}



                                    
%% TOOLS

% STEP 1
RetrieveListPapers_STEP_1_flag = true;  % carefull -> it will send requests to Science-Direct server

% STEP 2                                  
RequestPapersFromList_STEP_2_flag = false; % carefull -> it will send requests to Science-Direct server

% STEP 3
ExtractInfoFromPapers_STEP_3_flag = false; 
force_overwrite = true;
 
% STEP 4
PlotResults_STEP_4_flag = false; %1) # papers and keywords
filter_papers_keywords = {}; % if don't want to 
%filter_papers_keywords = {'biogeochemistry', 'geochemistry', 'chemistry', 'greenhouse', 'ion', 'anion',...
%        'cation','methane','mercur1y','carbon','organic','CO<sub>2</sub>','CH<sub>4</sub>''hydrate','gas','radiocarbon','hydrocarbon'};

% STEP 5
PlotMaps_STEP_5_flag = false;

% STEP 6
GenerateReport_STEP_6_flag = true;
only_title_and_highlights = false;


% additional settings
num_search_pages = 200;
pausetime = 10; % in seconds -> CAREFULL, DON'T PUT THIS LOWER THAN 10




%% call WebCrawler_ENGINE
myScopusApiKey = '3291a872bc42269b1594b782de7524c3';

show = 25; % this is the max of # of results that the scupos API allows (will return error if increased)


WebCrawler_ENGINE(folder_name_to_store_results,...
                main_keyword_searchengine_raw_multiple,...
                num_search_pages,...
                pausetime,...
                show,...
                myScopusApiKey,...
                RetrieveListPapers_STEP_1_flag,...,
                RequestPapersFromList_STEP_2_flag,...
                ExtractInfoFromPapers_STEP_3_flag,...
                force_overwrite,...
                PlotResults_STEP_4_flag,...
                filter_papers_keywords,...
                PlotMaps_STEP_5_flag,...
                GenerateReport_STEP_6_flag,...
                only_title_and_highlights);



